### ISSUE TITLE
Running OHIF VIEWER gives an error

### ISSUE THREAD

**Issue by xuwenhao2525** [knopkem/dicomweb-archive#23]
Running OHIF VIEWER gives an error, that is, 

running at this address: http://localhost: 5000/viewer/1.3.46.670589.5.2.10.10080.100088888886 

The reported error is: 

error: enoent: no such file or directory, open'd: \ dev \ dicomweb \ dicomweb-archive \ import \ samplestudy1 \ sample1'
[Nest] 15352  - 2023/03/27 15:11:25    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 15352  - 2023/03/27 15:11:25   ERROR [ExceptionsHandler] ENOENT: no such file or directory, open 'D:\dev\dicomweb\dicomweb-archive\import\SampleStudy1\sample2'
Error: ENOENT: no such file or directory, open 'D:\dev\dicomweb\dicomweb-archive\import\SampleStudy1\sample2'

It seems that this root directory is not my root directory，my root directory is 'D:\xunlei\dicomweb-archive-master(1)\dicomweb-archive-master\import\SampleStudy1'

**Comment by knopkem** [comment]
ok, weird, will have a look

**Comment by knopkem** [comment]
ok, I know what it is. I accidently committed the local sqlite files which contains the path to data. So to fix this issue, just delete the following files in your root:
dicomweb
dicomweb-shm
dicomweb-wal

After pull latest changes: git fetch && git pull
Then it should work.

**Comment by xuwenhao2525** [comment]
It's already working Thank you
