### ISSUE TITLE
QueryFailedError: Duplicate column name 'patient_patientName'

### ISSUE THREAD

**Issue by xuwenhao2525** [knopkem/dicomweb-archive#24]
Hello, I have encountered a problem when requesting this interface using Postman http://127.0.0.1:5000/rs/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060 , an error QueryFailedError will be reported: Duplicate column name 'patient_ 'patientName', what are the possible reasons for this?

**Comment by xuwenhao2525** [comment]
Also, it does not seem to support Cornerstone3D because images cannot be viewed in Cornerstone3D

**Comment by xuwenhao2525** [comment]
Hello, I tested it and found that when the database was replaced with MYSQL, it would have this problem, but SQLite would not have this problem. Could you test what the problem was? Thank you so much!

**Comment by knopkem** [comment]
Hi, this is an interesting (and genuine) bug that I can reproduce. Not sure what is the cause but will look into it and let you know.

**Comment by knopkem** [comment]
This seems to be a bug in the query builder from the library used typeorm, see https://github.com/typeorm/typeorm/issues/4603 and https://github.com/typeorm/typeorm/issues/2736. Luckily there seems to be a workaround (already applied). Can you try again, should work now.

**Comment by xuwenhao2525** [comment]
It's already working Thank you！
Can I obtain your email address because your open source project has provided great assistance to my current project. You must be familiar with relevant knowledge in the field of medical imaging, so I would like to ask you for an email address so that I can ask you for some questions? We look forward to your reply!

**Comment by knopkem** [comment]
Hi, just contact me via LinkedIn: https://www.linkedin.com/in/knopkem

transit ***@***.***> schrieb am So., 2. Apr. 2023, 07:42:
